services:
  postgres:
    image: postgres
    container_name: document_manager
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      #volumes:
      #- ./bbdd/01_scheme.sql:/docker-entrypoint-initdb.d/01_scheme.sql