name: Release Rust Application

on:
  pull_request:
    types: [ closed ]
    branches:
      - master


jobs:
  release:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.labels.*.name, 'release/')
    runs-on: ubuntu-latest
    defaults:
      working-directory: document_manager

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: '1.70'  # Cambia esto a la versión de Rust que necesitas

      - name: Get current version from Cargo.toml
        id: get_version
        run: |
          VERSION=$(grep '^version =' Cargo.toml | head -n 1 | awk -F ' = ' '{print $2}' | tr -d '"')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Determine new version
        id: determine_version
        run: |
          VERSION=${{ env.VERSION }}
          LABEL=$(echo "${{ github.event.pull_request.labels[*].name }}" | grep -oP '(?<=release\/)\w+')

          if [ -z "$LABEL" ]; then
            echo "No valid release label found."
            exit 1
          fi

          IFS="." read -r MAJOR MINOR PATCH <<< "$VERSION"

          case "$LABEL" in
            "major")
              MAJOR=$((MAJOR + 1))
              MINOR=0
              PATCH=0
              ;;
            "minor")
              MINOR=$((MINOR + 1))
              PATCH=0
              ;;
            "patch")
              PATCH=$((PATCH + 1))
              ;;
            *)
              echo "Invalid release label: $LABEL"
              exit 1
              ;;
          esac

          NEW_VERSION="$MAJOR.$MINOR.$PATCH"
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Update version in Cargo.toml
        run: |
          sed -i '0,/^version = /s/^version = "\(.*\)"/version = "${{ env.NEW_VERSION }}"/' Cargo.toml

      - name: Commit and push version update
        uses: EndBug/add-and-commit@v9
        with:
          author_name: 'GitHub Actions'
          author_email: 'actions@github.com'
          message: 'Update version to ${{ env.NEW_VERSION }}'
          add: 'Cargo.toml'
          push: true

      - name: Build the application
        run: cargo build --release

      - name: Create a release
        run: |
          TAG_NAME="v${{ env.NEW_VERSION }}"
          
          echo "Creating release for tag $TAG_NAME"

          # Tag the commit
          git tag -a "$TAG_NAME" -m "Release $TAG_NAME"
          git push origin "$TAG_NAME"

          # Create a GitHub release
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d "{\"tag_name\": \"$TAG_NAME\", \"name\": \"Release $TAG_NAME\", \"body\": \"Release notes for $TAG_NAME\"}" \
            https://api.github.com/repos/${{ github.repository }}/releases
